### ISSUE TITLE
Getting stuck with high FOV

### ISSUE THREAD

**Issue by FrederoxDev** [AmethystAPI/VidereLonge#4]
![image](https://github.com/ATXLtheAxolotl/VidereLonge/assets/69014593/c963ffea-5f54-468b-9f87-16f52478ebd4)

I zoomed and got stuck with a high FOV and now pressing c does nothing

**Comment by FrederoxDev** [comment]
Also as a note it never actually zoomed in, only zoomed out (made fov high)

**Comment by ATXLtheAxolotl** [comment]
Could you try this mod again with the latest release?

**Comment by ATXLtheAxolotl** [comment]
I’m closing this for now, my latest changes should prevent this possibility.
